"""Audit-grade exhaustive sweep for Theorem B.

For each planar triangulation generated by plantri (class: simple maximal
planar = A000109), we assert that a valid orientation exists AND we verify
the returned SAT model directly: decode the orientation and check
min(d+, d-) <= 1 at every vertex by plain degree counting (independent of
the encoding's correctness).

Audit properties:
  - every plantri output line must parse; a malformed line raises;
  - the plantri process exit code is checked;
  - per-instance model verification (not just the solver's boolean);
  - the run FAILS (nonzero exit) if any instance is infeasible;
  - per-order (and per-shard) counts are logged; full-order counts are
    asserted against OEIS A000109 here, sharded counts by the aggregator
    (theoremB_aggregate.py).

plantri location: set the PLANTRI environment variable or pass
--plantri PATH (plantri 5.5, https://users.cecs.anu.edu.au/~bdm/plantri/;
see verification/ENVIRONMENT.txt for the exact version, source patch and
build command used by the authors).

Usage:  python theoremB_audit.py N [res/mod] [--plantri PATH]
Writes: verification/theoremB/n{N}[_s{res}of{mod}].log
"""
import os
import subprocess
import sys
import time
from itertools import combinations
from pathlib import Path

from pysat.solvers import Cadical195


def _find_plantri():
    argv = sys.argv
    for i, a in enumerate(argv):
        if a == "--plantri" and i + 1 < len(argv):
            path = argv[i + 1]
            del argv[i:i + 2]
            return path
    path = os.environ.get("PLANTRI")
    if path:
        return path
    default = r"E:\math\vendor\plantri55\plantri.exe"
    if Path(default).exists():
        return default
    sys.exit("error: plantri not found. Set the PLANTRI environment "
             "variable or pass --plantri PATH.")


PLANTRI = _find_plantri()
HERE = Path(__file__).resolve().parent.parent
OUTDIR = HERE / "verification" / "theoremB"

A000109 = {4: 1, 5: 1, 6: 2, 7: 5, 8: 14, 9: 50, 10: 233, 11: 1249,
           12: 7595, 13: 49566, 14: 339722, 15: 2406841, 16: 17490241,
           17: 129664753}


def parse_ascii_strict(line):
    line = line.strip()
    head, _, rest = line.partition(" ")
    n = int(head)                      # raises on malformed
    parts = rest.split(",")
    if len(parts) != n:
        raise ValueError(f"bad plantri line: {line[:80]!r}")
    rot = [[ord(c) - ord("a") for c in p] for p in parts]
    for nb in rot:
        for v in nb:
            if not (0 <= v < n):
                raise ValueError(f"vertex out of range: {line[:80]!r}")
    return rot


def solve_and_verify(rot):
    """Return True iff a valid orientation exists AND the model checks out."""
    n = len(rot)
    edges = sorted({(min(u, v), max(u, v)) for u, nb in enumerate(rot) for v in nb})
    eidx = {e: i + 1 for i, e in enumerate(edges)}
    mE = len(edges)
    cnf = []
    for v in range(n):
        outs, ins = [], []
        for w in rot[v]:
            e = (min(v, w), max(v, w))
            lit = eidx[e] if v == e[0] else -eidx[e]
            outs.append(lit)
            ins.append(-lit)
        wv = mE + v + 1
        for a, b in combinations(outs, 2):
            cnf.append([-wv, -a, -b])
        for a, b in combinations(ins, 2):
            cnf.append([wv, -a, -b])
    with Cadical195(bootstrap_with=cnf) as s:
        if not s.solve():
            return False
        model = s.get_model()
    pos = set(l for l in model if l > 0)
    dplus = [0] * n
    dminus = [0] * n
    for (a, b), i in eidx.items():
        if i in pos:                   # oriented a -> b (low -> high)
            dplus[a] += 1
            dminus[b] += 1
        else:
            dplus[b] += 1
            dminus[a] += 1
    for v in range(n):
        if min(dplus[v], dminus[v]) > 1:
            raise AssertionError(f"model verification FAILED at vertex {v}")
    return True


def main():
    n = int(sys.argv[1])
    shard = sys.argv[2] if len(sys.argv) > 2 else None
    args = [PLANTRI, "-a", str(n)] + ([shard] if shard else [])
    OUTDIR.mkdir(parents=True, exist_ok=True)
    tag = f"n{n}" + (f"_s{shard.replace('/', 'of')}" if shard else "")
    t0 = time.time()
    proc = subprocess.Popen(args, stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE, text=True, bufsize=1 << 20)
    total = feasible = 0
    for line in proc.stdout:
        if not line.strip():
            continue
        rot = parse_ascii_strict(line)
        total += 1
        if solve_and_verify(rot):
            feasible += 1
        else:
            print(f"COUNTEREXAMPLE CANDIDATE: {line.strip()}", flush=True)
    proc.wait()
    err = proc.stderr.read()
    if proc.returncode != 0:
        raise RuntimeError(f"plantri exit code {proc.returncode}: {err[:200]}")
    dt = time.time() - t0
    msg = (f"n={n} shard={shard or 'full'} total={total} feasible={feasible} "
           f"model_verified={feasible} time={dt:.1f}s")
    (OUTDIR / f"{tag}.log").write_text(msg + "\n", encoding="utf-8")
    print(msg)
    if feasible != total:
        raise AssertionError(
            f"THEOREM B FAILS on {total - feasible} instance(s) at n={n} "
            f"shard={shard} -- see COUNTEREXAMPLE CANDIDATE lines above")
    if not shard and total != A000109[n]:
        raise AssertionError(f"count mismatch vs A000109: {total} != {A000109[n]}")


if __name__ == "__main__":
    main()
