"""Aggregator for the Theorem B audit logs.

Independently of the sweep driver, this script re-reads every log in
verification/theoremB/ and asserts, for each order n = 4..17:

  - the order is covered either by one full-order log, or by shards with
    indices forming exactly {0, 1, ..., mod-1} for a single modulus;
  - sum(total) over the order equals A000109[n];
  - sum(feasible) == sum(model_verified) == sum(total).

Any violation exits nonzero. On success writes verification/theoremB/
SUMMARY.md with the per-order table and the grand total.
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
LOGDIR = HERE / "verification" / "theoremB"

A000109 = {4: 1, 5: 1, 6: 2, 7: 5, 8: 14, 9: 50, 10: 233, 11: 1249,
           12: 7595, 13: 49566, 14: 339722, 15: 2406841, 16: 17490241,
           17: 129664753}

LINE = re.compile(
    r"n=(\d+) shard=(\S+) total=(\d+) feasible=(\d+) "
    r"model_verified=(\d+) time=([\d.]+)s")


def main():
    logs = sorted(p for p in LOGDIR.glob("n*.log"))
    if not logs:
        sys.exit("no logs found in " + str(LOGDIR))
    per_order = {}   # n -> list of (shard, total, feas, mv)
    for p in logs:
        text = p.read_text(encoding="utf-8").strip()
        m = LINE.fullmatch(text)
        if not m:
            sys.exit(f"unparseable log {p.name}: {text[:80]!r}")
        n, shard, tot, feas, mv = (int(m.group(1)), m.group(2),
                                   int(m.group(3)), int(m.group(4)),
                                   int(m.group(5)))
        per_order.setdefault(n, []).append((shard, tot, feas, mv))

    problems = []
    rows = []
    grand = 0
    for n in sorted(A000109):
        entries = per_order.get(n)
        if not entries:
            problems.append(f"n={n}: no logs")
            continue
        shards = [e[0] for e in entries]
        if shards == ["full"]:
            pass
        elif all("/" in s for s in shards):
            mods = {int(s.split("/")[1]) for s in shards}
            if len(mods) != 1:
                problems.append(f"n={n}: mixed moduli {mods}")
                continue
            mod = mods.pop()
            idx = sorted(int(s.split("/")[0]) for s in shards)
            if idx != list(range(mod)):
                problems.append(f"n={n}: shard set {idx} != 0..{mod-1}")
                continue
        else:
            problems.append(f"n={n}: mixed full/shard logs {shards}")
            continue
        T = sum(e[1] for e in entries)
        F = sum(e[2] for e in entries)
        M = sum(e[3] for e in entries)
        if T != A000109[n]:
            problems.append(f"n={n}: total {T} != A000109 {A000109[n]}")
        if F != T or M != T:
            problems.append(f"n={n}: feasible={F} model_verified={M} != total={T}")
        rows.append((n, len(entries), T, F, M))
        grand += T

    if problems:
        print("AGGREGATION FAILED:")
        for q in problems:
            print("  -", q)
        sys.exit(1)

    lines = ["# Theorem B audit summary", "",
             "| n | logs | total | feasible | model_verified |",
             "|---|------|-------|----------|----------------|"]
    for n, k, T, F, M in rows:
        lines.append(f"| {n} | {k} | {T} | {F} | {M} |")
    lines += ["", f"**Grand total: {grand} triangulations, all feasible, "
              f"all models degree-verified.**",
              "", "Counts match OEIS A000109 at every order; shard sets are "
              "complete. Generated by theoremB_aggregate.py."]
    (LOGDIR / "SUMMARY.md").write_text("\n".join(lines) + "\n",
                                       encoding="utf-8")
    print(f"AGGREGATION OK: {grand} instances, all orders complete "
          f"and verified. Summary written.")


if __name__ == "__main__":
    main()
